apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In
              values:
                - medium
